### ISSUE TITLE
Failed to execute "nmap"

### ISSUE THREAD

**Issue by goatatwork** [willdurand/nmap#11]
Hello,

I receive the following error:
FatalErrorException in Nmap.php line 62:
Call to a member function execute() on null

However, if I change line 62 of Nmap.php from this:
```
if ($executor->execute($this->executable) !== 0) {
```

to this:
```
if ($this->executor->execute($this->executable) !== 0) {
```

I seem to get past it.  Unfortunately, I then get this error:
RuntimeException in ProcessExecutor.php line 32:
Failed to execute "nmap"

It seems as though the nmap command is not being built up.  If I "hard code" the $executable variable on line 55 of Nmap.php to an actual nmap command, for instance....
```
    public function __construct(ProcessExecutor $executor = null, $outputFile = null, $executable = 'nmap 10.0.0.254')
```
I DO get what seems to be good data back.

Here is how I'm building up my Nmap object:
```
    public function nmapScan()
    {

		$hosts = \Nmap\Nmap::create()->enableVerbose()->scan([ 'myhost.mydomain.com' ]);
		
		$ports = $hosts->getOpenPorts();
                // dd($hosts);
		// dd($ports);

	}
```

Am I using this incorrectly?  It seems to completely disregard the host I'm telling it to scan, and unless I "hard code" the hostname into line 55 of Nmap.php, it fails because it's trying to execute 'nmap' alone with only prints the command help information.

If I can provide other/more data, I will be happy to.  Sorry if this isn't the prescribed way to submit this issue.  I'm new to pull requests and issue tracking on github, so if I should do this differently, just let me know and I'll be happy to.

Thanks for what looks like a really awesome package!  Any help you can provide will be greatly appreciated.

Oh, and this is being used in a Laravel 5.1 project.  My test box is running PHP 5.5.20.

**Comment by alister** [comment]
If Nmap (Nmap 5.21, on Linux, 'Ubuntu 12.04.5 LTS') is run without parameters (see https://github.com/nmap/nmap/blame/99b0f9f8fbeb02b84959ce3fdf87896c5ce878ee/nmap.cc#L1720), then it will `exit(-1)`, which shows on a Linux command line as a '255' return (`echo $?`). 

Since the execution occurs in `ProcessExecutor`, it shows as 'Failed to execute ...'.

However, If the initial test-run is done as `nmap -h`, then the return value is 0.

**Comment by mtdavidson** [comment]
I've created a pull request to fix this re @alister comments seems introducing the -h solves it in the simplest cleanest way. Checking the response codes could be another option but would mean changing code in both the Nmap constructor and the ProcessExecute execute method.

**Comment by willdurand** [comment]
fixed
