### ISSUE TITLE
Can only install one of: symfony/process[v2.8.0, v3.0.6].

### ISSUE THREAD

**Issue by herzcthu** [willdurand/nmap#17]
I'm trying to use nmap in laravel 5.2. symfony/process v3.0.6 already installed as dependency for laravel 5.2.
nmap require synfony/process ~2.0 . I can't use nmap because dependency conflict problem.

**Comment by Falc** [comment]
This has been solved in #21 but there is no new release yet, so it requires to use `dev-master` in `composer.json`.

/cc: @willdurand

**Comment by willdurand** [comment]
just pushed a new tag, sorry for the delay :(
