### ISSUE TITLE
Timeout on larger scans

### ISSUE THREAD

**Issue by loeken** [willdurand/nmap#22]
great project so far!

I only have 1 little issue that when i run scans on hosts with a lot of ports i exceed the 60 second default timeout in the ProcessExecutor.php

My suggestion in Nmap.php add $timeout = 60 when initializing the class and passing that on to the ->execute($command, $timeout) method.

Inside the processExecutor create the new Process() like this:

$process = new Process($command,NULL,NULL,NULL,$timeout);

If you want to i could probably sent a pull request or something 

greetings 
loeken

**Comment by willdurand** [comment]
Yup, sounds good to me! Would you like to write a PR?

**Comment by loeken** [comment]
I think i created one: https://github.com/willdurand/nmap/pull/23

(first time, since its only a few changes i didn't create a seperate branch )

**Comment by elition31** [comment]
Is it possible to add this functionality ?

**Comment by willdurand** [comment]
should be fixed I guess.
