### ISSUE TITLE
Nmap is not working in laravel

### ISSUE THREAD

**Issue by fani385** [willdurand/nmap#31]
Failed to execute "nmap -h"
'nmap' is not recognized as an internal or external command,
operable program or batch file.

(1/1) RuntimeExceptionFailed to execute "nmap -h"'nmap' is not recognized as an internal or external command,operable program or batch file.
--
in ProcessExecutor.php line 31
at ProcessExecutor->execute('nmap -h')in Nmap.php line 62
at Nmap->__construct()in Nmap.php line 45
at Nmap::create()in UserController.php line 22
at UserController->index()
at call_user_func_array(array(object(UserController), 'index'), array())in Controller.php line 55
at Controller->callAction('index', array())in ControllerDispatcher.php line 44

**Comment by repat** [comment]
Which PHP version and Laravel version are you using?

**Comment by fani385** [comment]
PHP version 7.2 Laravel version 5.6

**Comment by repat** [comment]
On first glance this doesn't seem to be a problem with `nmap` but with your PHP installation. Can I assume you've done your share of googleing and tried e.g. this: https://stackoverflow.com/questions/31291317/php-is-not-recognized-as-an-internal-or-external-command-in-command-prompt ?

**Comment by fani385** [comment]
My laravel app and other packages are working fine.

**Comment by kimhaafi** [comment]
I had this issue when running on a VM, be sure to have nmap installed on the system running the laravel project. Might be silly but nmap need på be installed for php to be able to execute, as specified in the error "'nmap' is not recognized as an internal or external command,operable program or batch file."

**Comment by peter279k** [comment]
The nmap is the command and it's not installed in Linux system by default.

You should install the `nmap` firstly.

**Comment by repat** [comment]
What @peter279k said: you need to install nmap first, e.g.
`brew install nmap` (MacOS)
`apt-get install nmap` (Debian/Ubuntu)
Or google how to do it on your operating system :-)
