### ISSUE TITLE
Symfony 5 support

### ISSUE THREAD

**Issue by DavidGarciaCat** [willdurand/nmap#40]
Hello,

Would be possible adding Symfony 5 support too, please, in the same way we have support for Symfony 2, 3, and 4?

Alternatively, maybe is worth "clean up" the unmaintained versions and just keep support for Symfony 4 and 5?

Cheers,

**Comment by wvdongen** [comment]
This fork is maintained and Symfony 5 https://github.com/DavidGoodwin/nmap/

**Comment by DavidGarciaCat** [comment]
:+1: nice! thanks!
